// Darrow Report schema — Zod runtime + JSON Schema for Anthropic tool.
//
// CORE module v3.1 (schema_version "core_v3"): 17 sections, 11 with structured
// callouts ({ prose, protocols?, warning_signals? }), 5 prose-only strings.
// Accepts either shape (string OR section object) for backward compat with
// reports stored before v3.1 — getCoreSectionProse() in the template handles both.
//
// CORE module v4 (schema_version "core_v4"): 17 generated body section keys
// (operating_mode added at position 3, cover_tagline promoted to cover sub-field),
// per-section structured fields (opening_line, scenario, key_insight, proof_tags),
// special shapes for before_after / executive_summary / next_step / vitality_baseline.
// Uses strict() to reject unknown top-level keys (e.g. recommended_next_module).
//
// Add-on modules retain the legacy shape for runtime compatibility.

import { z } from "zod";

const ModuleSnapshotSchema = z.object({
  main_pattern: z.string().min(1),
  main_strength: z.string().min(1),
  main_risk: z.string().min(1),
  practical_protocol: z.string().min(1),
  next_step: z.string().min(1),
});

// ─────────────────────────────────────────────────────────────
// CORE v3.1 — structured callout sections
// ─────────────────────────────────────────────────────────────

export const CORE_V3_SECTIONS_WITH_PROTOCOLS = [
  "core_architecture",
  "battery",
  "social_interface",
  "numerology_code",
  "cognitive_style",
  "drive_and_rhythm",
  "professional_archetype",
  "money_and_value",
  "relationship_baseline",
  "vitality_baseline",
  "environment_and_resonance",
] as const;

export const CORE_V3_SECTIONS_WITH_WARNINGS = [
  "battery",
  "professional_archetype",
  "shadow_and_friction",
] as const;

export const CORE_V3_PROSE_ONLY_SECTIONS = [
  "cover_tagline",
  "orientation",
  "before_after",
  "executive_summary",
  "next_step",
] as const;

const ProtocolObject = z.object({
  title: z.string().min(1),
  body: z.string().min(1),
});

const SectionObjectSchema = z
  .object({
    prose: z.string(),
    protocols: z.array(ProtocolObject).optional(),
    warning_signals: z.array(z.string()).optional(),
  })
  .passthrough();

// Accept either a raw string (legacy / prose-only) or the structured object.
const CoreSectionField = z.union([z.string(), SectionObjectSchema]);

// Updated v3.1 minimums (prose length, not full object stringified).
// These are per-section minimum prose char counts.
const CORE_V3_MIN: Record<string, number> = {
  cover_tagline: 50,
  orientation: 800,
  core_architecture: 1100,
  battery: 900,
  social_interface: 800,
  numerology_code: 1000,
  cognitive_style: 800,
  drive_and_rhythm: 800,
  professional_archetype: 900,
  money_and_value: 800,
  relationship_baseline: 800,
  vitality_baseline: 750,
  environment_and_resonance: 750,
  shadow_and_friction: 1000,
  before_after: 500,
  executive_summary: 1100,
  next_step: 350,
};

function sectionProse(v: unknown): string {
  if (typeof v === "string") return v;
  if (v && typeof v === "object" && typeof (v as any).prose === "string") return (v as any).prose;
  return "";
}

export const CoreV3Schema = z
  .object({
    schema_version: z.literal("core_v3"),
    cover_tagline: CoreSectionField,
    orientation: CoreSectionField,
    core_architecture: CoreSectionField,
    battery: CoreSectionField,
    social_interface: CoreSectionField,
    numerology_code: CoreSectionField,
    cognitive_style: CoreSectionField,
    drive_and_rhythm: CoreSectionField,
    professional_archetype: CoreSectionField,
    money_and_value: CoreSectionField,
    relationship_baseline: CoreSectionField,
    vitality_baseline: CoreSectionField,
    environment_and_resonance: CoreSectionField,
    shadow_and_friction: CoreSectionField,
    before_after: CoreSectionField,
    executive_summary: CoreSectionField,
    next_step: CoreSectionField,
    proof_tags: z.array(z.string()).optional(),
    module_snapshot: ModuleSnapshotSchema.optional(),
    color_palette: z.array(z.string()).optional(),
    color_names: z.array(z.string()).optional(),
  })
  .superRefine((mod, ctx) => {
    for (const [k, min] of Object.entries(CORE_V3_MIN)) {
      const prose = sectionProse((mod as any)[k]);
      const actual = prose.length;
      if (actual < min) {
        console.warn("[schema] CORE v3.1 section under min prose length", {
          section: k,
          actual,
          expected: min,
          status: "FAILED",
        });
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: [k],
          message: `CORE.${k} prose too short: ${actual} chars < ${min} required`,
        });
      }
    }
  });

// ─────────────────────────────────────────────────────────────
// CORE v4 — per-section structured fields, special shapes
// ─────────────────────────────────────────────────────────────

// Verbatim vitality disclaimer — static constant injected by template,
// never generated by Claude. Schema allows the exact literal if present.
export const CORE_V4_DISCLAIMER_TEXT =
  "This is interpretive orientation, not medical advice. Consult a qualified healthcare professional for any health concerns." as const;

// Locked executive_summary block labels (gold sample, locked 2026-06-02).
const executiveSummaryLabelEnum = z.enum([
  "YOUR CORE ADVANTAGE",
  "YOUR PRIMARY SENSITIVITY",
  "YOUR DECISION FORMULA",
  "THE CORE CONCLUSION",
  "CURRENT CYCLE",
  "THE NEXT LEVEL",
]);
export const EXECUTIVE_SUMMARY_LABELS = executiveSummaryLabelEnum.options;

// Locked closing pillar titles (gold sample, locked 2026-06-02).
const closingPillarTitleEnum = z.enum([
  "TRUST THE SIGNAL",
  "BUILD THE BASE",
  "RESPECT THE CYCLE",
  "HONOR THE SPACE",
]);
export const CLOSING_PILLAR_TITLES = closingPillarTitleEnum.options;

// The 17 generated CORE body section keys in fixed order.
// cover_tagline is a cover sub-field and is NOT in this list.
export const CORE_V4_BODY_SECTION_KEYS = [
  "orientation",
  "core_architecture",
  "operating_mode",
  "battery",
  "social_interface",
  "numerology_code",
  "cognitive_style",
  "drive_and_rhythm",
  "professional_archetype",
  "money_and_value",
  "relationship_baseline",
  "vitality_baseline",
  "environment_and_resonance",
  "shadow_and_friction",
  "before_after",
  "executive_summary",
  "next_step",
] as const;

export const CORE_V4_SECTIONS_WITH_PROTOCOLS = [
  "core_architecture",
  "operating_mode",
  "battery",
  "social_interface",
  "numerology_code",
  "cognitive_style",
  "drive_and_rhythm",
  "professional_archetype",
  "money_and_value",
  "relationship_baseline",
  "vitality_baseline",
  "environment_and_resonance",
  "shadow_and_friction",
] as const;

export const CORE_V4_SECTIONS_WITH_WARNINGS = [
  "battery",
  "vitality_baseline",
  "shadow_and_friction",
] as const;

// orientation has no protocol/warning in the generation spec.
// before_after / executive_summary / next_step use special shapes.
export const CORE_V4_PROSE_ONLY_SECTIONS = ["orientation"] as const;

// Standard v4 section — all regular body sections use this shape.
// Fields are schema-optional; generation prompt marks required fields
// per section (handled in B2 prompt phase, not enforced here).
const CoreV4SectionSchema = z.object({
  opening_line: z.string().max(120).optional(),
  scenario: z.string().optional(),
  prose: z.string().min(1),
  key_insight: z.string().optional(),
  protocols: z.array(ProtocolObject).optional(),
  warning_signals: z.array(z.string()).optional(),
  proof_tags: z.array(z.string()).max(5).optional(),
});

// vitality_baseline extends standard with optional verbatim disclaimer.
const CoreV4VitalitySchema = CoreV4SectionSchema.extend({
  disclaimer: z.literal(CORE_V4_DISCLAIMER_TEXT).optional(),
});

// before_after — 2 Before/After pairs (locked length 2).
const CoreV4BeforeAfterPairSchema = z.object({
  before: z.string().min(1),
  after: z.string().min(1),
});

const CoreV4BeforeAfterSchema = z.object({
  opening_line: z.string().max(120).optional(),
  scenario: z.string().optional(),
  prose: z.string().optional(),
  key_insight: z.string().optional(),
  before_after_pairs: z.array(CoreV4BeforeAfterPairSchema).length(2),
  proof_tags: z.array(z.string()).max(5).optional(),
});

// executive_summary — 6 labeled blocks in exact locked order (gold sample, 2026-06-02).
// z.tuple enforces exact label at each position: no duplicates, no reordering.
const CoreV4ExecutiveSummarySchema = z.object({
  opening_line: z.string().max(120).optional(),
  prose: z.string().optional(),
  key_insight: z.string().optional(),
  executive_summary_blocks: z.tuple([
    z.object({ label: z.literal("YOUR CORE ADVANTAGE"), content: z.string().min(1) }),
    z.object({ label: z.literal("YOUR PRIMARY SENSITIVITY"), content: z.string().min(1) }),
    z.object({ label: z.literal("YOUR DECISION FORMULA"), content: z.string().min(1) }),
    z.object({ label: z.literal("THE CORE CONCLUSION"), content: z.string().min(1) }),
    z.object({ label: z.literal("CURRENT CYCLE"), content: z.string().min(1) }),
    z.object({ label: z.literal("THE NEXT LEVEL"), content: z.string().min(1) }),
  ]),
  proof_tags: z.array(z.string()).max(5).optional(),
});

// next_step — 4 closing pillars in exact locked order (gold sample, 2026-06-02).
// z.tuple enforces exact title at each position: no duplicates, no reordering.
const CoreV4NextStepSchema = z.object({
  opening_line: z.string().max(120).optional(),
  prose: z.string().optional(),
  key_insight: z.string().optional(),
  closing_pillars: z.tuple([
    z.object({ title: z.literal("TRUST THE SIGNAL"), prose: z.string().min(1) }),
    z.object({ title: z.literal("BUILD THE BASE"), prose: z.string().min(1) }),
    z.object({ title: z.literal("RESPECT THE CYCLE"), prose: z.string().min(1) }),
    z.object({ title: z.literal("HONOR THE SPACE"), prose: z.string().min(1) }),
  ]),
  proof_tags: z.array(z.string()).max(5).optional(),
});

// CoreV4Schema — strict() rejects unknown top-level keys (no cross-sell fields,
// no closing, no recommended_next_module).
// cover_tagline is a variable cover sub-field, not a body section key.
export const CoreV4Schema = z
  .object({
    schema_version: z.literal("core_v4"),
    cover_tagline: z.string().min(1),
    orientation: CoreV4SectionSchema,
    core_architecture: CoreV4SectionSchema,
    operating_mode: CoreV4SectionSchema,
    battery: CoreV4SectionSchema,
    social_interface: CoreV4SectionSchema,
    numerology_code: CoreV4SectionSchema,
    cognitive_style: CoreV4SectionSchema,
    drive_and_rhythm: CoreV4SectionSchema,
    professional_archetype: CoreV4SectionSchema,
    money_and_value: CoreV4SectionSchema,
    relationship_baseline: CoreV4SectionSchema,
    vitality_baseline: CoreV4VitalitySchema,
    environment_and_resonance: CoreV4SectionSchema,
    shadow_and_friction: CoreV4SectionSchema,
    before_after: CoreV4BeforeAfterSchema,
    executive_summary: CoreV4ExecutiveSummarySchema,
    next_step: CoreV4NextStepSchema,
  })
  .strict();

// ─────────────────────────────────────────────────────────────
// Legacy / add-on module shape
// ─────────────────────────────────────────────────────────────

const LegacyModuleSchema = z.object({
  opening: z.string().min(40),
  architecture: z.string().min(80),
  mechanic: z.string().min(40),
  timing: z.string().min(40),
  protocols: z.string().min(80),
  shadow: z.string().min(40),
  before_after: z.string().min(30),
  next: z.string().min(20),
  proof_tags: z.array(z.string()).min(1),
  module_snapshot: ModuleSnapshotSchema.optional(),
  color_palette: z.array(z.string()).optional(),
  color_names: z.array(z.string()).optional(),
  module_opening: z.string().optional(),
  primary_architecture: z.string().optional(),
  mechanism: z.string().optional(),
  key_pattern: z.string().optional(),
  summary: z.string().optional(),
  bridge: z.string().optional(),
});

const ModuleSchema = z.union([CoreV4Schema, CoreV3Schema, LegacyModuleSchema]);

export const DarrowReportSchema = z.object({
  client_name: z.string().min(1),
  generated_modules: z.array(z.string()).min(1),
  client_snapshot: z.object({
    pattern_name: z.string().min(1),
    core_pattern: z.string().min(1),
    unique_signature: z.string().min(1),
    primary_strength: z.string().min(1),
    pressure_point: z.string().min(1),
    best_operating_rhythm: z.string().min(1),
    current_timing_theme: z.string().min(1),
    practical_focus: z.string().min(1),
    recommended_next_module: z.string().min(1),
  }),
  modules: z.record(z.string(), ModuleSchema),
  closing: z.object({
    executive_summary: z.string().min(40),
    recommended_next_module: z.string().min(1),
    grand_synthesis: z.string().optional(),
  }),
});

export type DarrowReport = z.infer<typeof DarrowReportSchema>;
export type DarrowModule = z.infer<typeof LegacyModuleSchema>;
export type DarrowCoreV3 = z.infer<typeof CoreV3Schema>;
export type DarrowCoreV4 = z.infer<typeof CoreV4Schema>;
export type DarrowCoreSection = z.infer<typeof CoreSectionField>;

// Helper used across template + diagnostics. Always returns the prose text
// for a CORE v3 section whether it is stored as a string (legacy) or as the
// new {prose, protocols?, warning_signals?} object.
export function getCoreSectionProse(field: unknown): string {
  return sectionProse(field);
}
export function getCoreSectionProtocols(field: unknown): Array<{ title: string; body: string }> {
  if (field && typeof field === "object" && Array.isArray((field as any).protocols)) {
    return (field as any).protocols as Array<{ title: string; body: string }>;
  }
  return [];
}
export function getCoreSectionWarnings(field: unknown): string[] {
  if (field && typeof field === "object" && Array.isArray((field as any).warning_signals)) {
    return ((field as any).warning_signals as unknown[]).map((x) => String(x));
  }
  return [];
}

// ─────────────────────────────────────────────────────────────
// Anthropic tool JSON Schema — lockstep with Zod.
// CORE v3 sections that carry callouts emit as objects; prose-only stays string.
// CORE v4 JSON Schema is defined in B2 (core-split.server.ts prompt phase).
// ─────────────────────────────────────────────────────────────

const protocolJsonSchema = {
  type: "object",
  required: ["title", "body"],
  properties: { title: { type: "string" }, body: { type: "string" } },
} as const;

function sectionObjectJsonSchema(opts: { protocols?: boolean; warnings?: boolean }) {
  const properties: Record<string, any> = { prose: { type: "string" } };
  const required: string[] = ["prose"];
  if (opts.protocols) properties.protocols = { type: "array", items: protocolJsonSchema };
  if (opts.warnings) properties.warning_signals = { type: "array", items: { type: "string" } };
  return { type: "object", required, properties };
}

const SECTIONS_WITH_PROTOCOLS_SET = new Set<string>(CORE_V3_SECTIONS_WITH_PROTOCOLS);
const SECTIONS_WITH_WARNINGS_SET = new Set<string>(CORE_V3_SECTIONS_WITH_WARNINGS);

export function coreSectionJsonSchemaFor(key: string) {
  const hasP = SECTIONS_WITH_PROTOCOLS_SET.has(key);
  const hasW = SECTIONS_WITH_WARNINGS_SET.has(key);
  if (!hasP && !hasW) return { type: "string" } as const;
  return sectionObjectJsonSchema({ protocols: hasP, warnings: hasW });
}

const coreV3Props = (() => {
  const allKeys = [
    "cover_tagline",
    "orientation",
    "core_architecture",
    "battery",
    "social_interface",
    "numerology_code",
    "cognitive_style",
    "drive_and_rhythm",
    "professional_archetype",
    "money_and_value",
    "relationship_baseline",
    "vitality_baseline",
    "environment_and_resonance",
    "shadow_and_friction",
    "before_after",
    "executive_summary",
    "next_step",
  ];
  const properties: Record<string, any> = {
    schema_version: { type: "string", enum: ["core_v3"] },
    proof_tags: { type: "array", items: { type: "string" } },
  };
  for (const k of allKeys) properties[k] = coreSectionJsonSchemaFor(k);
  return {
    type: "object",
    required: ["schema_version", ...allKeys],
    properties,
  };
})();

const legacyModuleProps = {
  type: "object",
  required: [
    "opening",
    "architecture",
    "mechanic",
    "timing",
    "protocols",
    "shadow",
    "before_after",
    "next",
    "proof_tags",
  ],
  properties: {
    opening: { type: "string" },
    architecture: { type: "string" },
    mechanic: { type: "string" },
    timing: { type: "string" },
    protocols: { type: "string" },
    shadow: { type: "string" },
    before_after: { type: "string" },
    next: { type: "string" },
    proof_tags: { type: "array", items: { type: "string" }, minItems: 1 },
    module_snapshot: {
      type: "object",
      required: ["main_pattern", "main_strength", "main_risk", "practical_protocol", "next_step"],
      properties: {
        main_pattern: { type: "string" },
        main_strength: { type: "string" },
        main_risk: { type: "string" },
        practical_protocol: { type: "string" },
        next_step: { type: "string" },
      },
    },
    color_palette: { type: "array", items: { type: "string" } },
    color_names: { type: "array", items: { type: "string" } },
  },
} as const;

export const darrowReportJsonSchema = {
  type: "object",
  required: ["client_name", "generated_modules", "client_snapshot", "modules", "closing"],
  properties: {
    client_name: { type: "string" },
    generated_modules: { type: "array", items: { type: "string" }, minItems: 1 },
    client_snapshot: {
      type: "object",
      required: [
        "pattern_name",
        "core_pattern",
        "unique_signature",
        "primary_strength",
        "pressure_point",
        "best_operating_rhythm",
        "current_timing_theme",
        "practical_focus",
        "recommended_next_module",
      ],
      properties: {
        pattern_name: { type: "string" },
        core_pattern: { type: "string" },
        unique_signature: { type: "string" },
        primary_strength: { type: "string" },
        pressure_point: { type: "string" },
        best_operating_rhythm: { type: "string" },
        current_timing_theme: { type: "string" },
        practical_focus: { type: "string" },
        recommended_next_module: { type: "string" },
      },
    },
    modules: {
      type: "object",
      description:
        "Keys are module codes. CORE uses v3.1 shape (schema_version=core_v3, structured callout objects for 11 sections). Add-ons use the legacy shape.",
      properties: {
        CORE: coreV3Props,
        LOVE: legacyModuleProps,
        MONEY: legacyModuleProps,
        BODY: legacyModuleProps,
        YEAR: legacyModuleProps,
        STYLE: legacyModuleProps,
        PLACE: legacyModuleProps,
      },
    },
    closing: {
      type: "object",
      required: ["executive_summary", "recommended_next_module"],
      properties: {
        executive_summary: { type: "string" },
        recommended_next_module: { type: "string" },
        grand_synthesis: { type: "string" },
      },
    },
  },
} as const;
