/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SampleRouteImport } from './routes/sample'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultReportTokenRouteImport } from './routes/result.$reportToken'
import { Route as DownloadReportTokenRouteImport } from './routes/download.$reportToken'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicJobsResendReadyEmailRouteImport } from './routes/api/public/jobs/resend-ready-email'
import { Route as ApiPublicJobsProcessGenerationRouteImport } from './routes/api/public/jobs/process-generation'
import { Route as ApiPublicHealthGenerationPipelineRouteImport } from './routes/api/public/health/generation-pipeline'
import { Route as ApiPublicDebugCoreV4RunRouteImport } from './routes/api/public/debug/core-v4-run'
import { Route as ApiPublicDebugCoreV4RenderRouteImport } from './routes/api/public/debug/core-v4-render'
import { Route as ApiPublicDebugCoreV3RunRouteImport } from './routes/api/public/debug/core-v3-run'
import { Route as ApiPublicDebugBuildStatusRouteImport } from './routes/api/public/debug/build-status'
import { Route as ApiPublicDebugBuildMarkerRouteImport } from './routes/api/public/debug/build-marker'
import { Route as ApiPublicDebugAstroProbeRouteImport } from './routes/api/public/debug/astro-probe'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleRoute = SampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultReportTokenRoute = ResultReportTokenRouteImport.update({
  id: '/result/$reportToken',
  path: '/result/$reportToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadReportTokenRoute = DownloadReportTokenRouteImport.update({
  id: '/download/$reportToken',
  path: '/download/$reportToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsResendReadyEmailRoute =
  ApiPublicJobsResendReadyEmailRouteImport.update({
    id: '/api/public/jobs/resend-ready-email',
    path: '/api/public/jobs/resend-ready-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsProcessGenerationRoute =
  ApiPublicJobsProcessGenerationRouteImport.update({
    id: '/api/public/jobs/process-generation',
    path: '/api/public/jobs/process-generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthGenerationPipelineRoute =
  ApiPublicHealthGenerationPipelineRouteImport.update({
    id: '/api/public/health/generation-pipeline',
    path: '/api/public/health/generation-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugCoreV4RunRoute = ApiPublicDebugCoreV4RunRouteImport.update({
  id: '/api/public/debug/core-v4-run',
  path: '/api/public/debug/core-v4-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugCoreV4RenderRoute =
  ApiPublicDebugCoreV4RenderRouteImport.update({
    id: '/api/public/debug/core-v4-render',
    path: '/api/public/debug/core-v4-render',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugCoreV3RunRoute = ApiPublicDebugCoreV3RunRouteImport.update({
  id: '/api/public/debug/core-v3-run',
  path: '/api/public/debug/core-v3-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugBuildStatusRoute =
  ApiPublicDebugBuildStatusRouteImport.update({
    id: '/api/public/debug/build-status',
    path: '/api/public/debug/build-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugBuildMarkerRoute =
  ApiPublicDebugBuildMarkerRouteImport.update({
    id: '/api/public/debug/build-marker',
    path: '/api/public/debug/build-marker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugAstroProbeRoute =
  ApiPublicDebugAstroProbeRouteImport.update({
    id: '/api/public/debug/astro-probe',
    path: '/api/public/debug/astro-probe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/generating': typeof GeneratingRoute
  '/privacy': typeof PrivacyRoute
  '/sample': typeof SampleRoute
  '/terms': typeof TermsRoute
  '/download/$reportToken': typeof DownloadReportTokenRoute
  '/result/$reportToken': typeof ResultReportTokenRoute
  '/api/public/debug/astro-probe': typeof ApiPublicDebugAstroProbeRoute
  '/api/public/debug/build-marker': typeof ApiPublicDebugBuildMarkerRoute
  '/api/public/debug/build-status': typeof ApiPublicDebugBuildStatusRoute
  '/api/public/debug/core-v3-run': typeof ApiPublicDebugCoreV3RunRoute
  '/api/public/debug/core-v4-render': typeof ApiPublicDebugCoreV4RenderRoute
  '/api/public/debug/core-v4-run': typeof ApiPublicDebugCoreV4RunRoute
  '/api/public/health/generation-pipeline': typeof ApiPublicHealthGenerationPipelineRoute
  '/api/public/jobs/process-generation': typeof ApiPublicJobsProcessGenerationRoute
  '/api/public/jobs/resend-ready-email': typeof ApiPublicJobsResendReadyEmailRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/generating': typeof GeneratingRoute
  '/privacy': typeof PrivacyRoute
  '/sample': typeof SampleRoute
  '/terms': typeof TermsRoute
  '/download/$reportToken': typeof DownloadReportTokenRoute
  '/result/$reportToken': typeof ResultReportTokenRoute
  '/api/public/debug/astro-probe': typeof ApiPublicDebugAstroProbeRoute
  '/api/public/debug/build-marker': typeof ApiPublicDebugBuildMarkerRoute
  '/api/public/debug/build-status': typeof ApiPublicDebugBuildStatusRoute
  '/api/public/debug/core-v3-run': typeof ApiPublicDebugCoreV3RunRoute
  '/api/public/debug/core-v4-render': typeof ApiPublicDebugCoreV4RenderRoute
  '/api/public/debug/core-v4-run': typeof ApiPublicDebugCoreV4RunRoute
  '/api/public/health/generation-pipeline': typeof ApiPublicHealthGenerationPipelineRoute
  '/api/public/jobs/process-generation': typeof ApiPublicJobsProcessGenerationRoute
  '/api/public/jobs/resend-ready-email': typeof ApiPublicJobsResendReadyEmailRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/generating': typeof GeneratingRoute
  '/privacy': typeof PrivacyRoute
  '/sample': typeof SampleRoute
  '/terms': typeof TermsRoute
  '/download/$reportToken': typeof DownloadReportTokenRoute
  '/result/$reportToken': typeof ResultReportTokenRoute
  '/api/public/debug/astro-probe': typeof ApiPublicDebugAstroProbeRoute
  '/api/public/debug/build-marker': typeof ApiPublicDebugBuildMarkerRoute
  '/api/public/debug/build-status': typeof ApiPublicDebugBuildStatusRoute
  '/api/public/debug/core-v3-run': typeof ApiPublicDebugCoreV3RunRoute
  '/api/public/debug/core-v4-render': typeof ApiPublicDebugCoreV4RenderRoute
  '/api/public/debug/core-v4-run': typeof ApiPublicDebugCoreV4RunRoute
  '/api/public/health/generation-pipeline': typeof ApiPublicHealthGenerationPipelineRoute
  '/api/public/jobs/process-generation': typeof ApiPublicJobsProcessGenerationRoute
  '/api/public/jobs/resend-ready-email': typeof ApiPublicJobsResendReadyEmailRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/generating'
    | '/privacy'
    | '/sample'
    | '/terms'
    | '/download/$reportToken'
    | '/result/$reportToken'
    | '/api/public/debug/astro-probe'
    | '/api/public/debug/build-marker'
    | '/api/public/debug/build-status'
    | '/api/public/debug/core-v3-run'
    | '/api/public/debug/core-v4-render'
    | '/api/public/debug/core-v4-run'
    | '/api/public/health/generation-pipeline'
    | '/api/public/jobs/process-generation'
    | '/api/public/jobs/resend-ready-email'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/generating'
    | '/privacy'
    | '/sample'
    | '/terms'
    | '/download/$reportToken'
    | '/result/$reportToken'
    | '/api/public/debug/astro-probe'
    | '/api/public/debug/build-marker'
    | '/api/public/debug/build-status'
    | '/api/public/debug/core-v3-run'
    | '/api/public/debug/core-v4-render'
    | '/api/public/debug/core-v4-run'
    | '/api/public/health/generation-pipeline'
    | '/api/public/jobs/process-generation'
    | '/api/public/jobs/resend-ready-email'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/generating'
    | '/privacy'
    | '/sample'
    | '/terms'
    | '/download/$reportToken'
    | '/result/$reportToken'
    | '/api/public/debug/astro-probe'
    | '/api/public/debug/build-marker'
    | '/api/public/debug/build-status'
    | '/api/public/debug/core-v3-run'
    | '/api/public/debug/core-v4-render'
    | '/api/public/debug/core-v4-run'
    | '/api/public/health/generation-pipeline'
    | '/api/public/jobs/process-generation'
    | '/api/public/jobs/resend-ready-email'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GeneratingRoute: typeof GeneratingRoute
  PrivacyRoute: typeof PrivacyRoute
  SampleRoute: typeof SampleRoute
  TermsRoute: typeof TermsRoute
  DownloadReportTokenRoute: typeof DownloadReportTokenRoute
  ResultReportTokenRoute: typeof ResultReportTokenRoute
  ApiPublicDebugAstroProbeRoute: typeof ApiPublicDebugAstroProbeRoute
  ApiPublicDebugBuildMarkerRoute: typeof ApiPublicDebugBuildMarkerRoute
  ApiPublicDebugBuildStatusRoute: typeof ApiPublicDebugBuildStatusRoute
  ApiPublicDebugCoreV3RunRoute: typeof ApiPublicDebugCoreV3RunRoute
  ApiPublicDebugCoreV4RenderRoute: typeof ApiPublicDebugCoreV4RenderRoute
  ApiPublicDebugCoreV4RunRoute: typeof ApiPublicDebugCoreV4RunRoute
  ApiPublicHealthGenerationPipelineRoute: typeof ApiPublicHealthGenerationPipelineRoute
  ApiPublicJobsProcessGenerationRoute: typeof ApiPublicJobsProcessGenerationRoute
  ApiPublicJobsResendReadyEmailRoute: typeof ApiPublicJobsResendReadyEmailRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$reportToken': {
      id: '/result/$reportToken'
      path: '/result/$reportToken'
      fullPath: '/result/$reportToken'
      preLoaderRoute: typeof ResultReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$reportToken': {
      id: '/download/$reportToken'
      path: '/download/$reportToken'
      fullPath: '/download/$reportToken'
      preLoaderRoute: typeof DownloadReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/resend-ready-email': {
      id: '/api/public/jobs/resend-ready-email'
      path: '/api/public/jobs/resend-ready-email'
      fullPath: '/api/public/jobs/resend-ready-email'
      preLoaderRoute: typeof ApiPublicJobsResendReadyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/process-generation': {
      id: '/api/public/jobs/process-generation'
      path: '/api/public/jobs/process-generation'
      fullPath: '/api/public/jobs/process-generation'
      preLoaderRoute: typeof ApiPublicJobsProcessGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/generation-pipeline': {
      id: '/api/public/health/generation-pipeline'
      path: '/api/public/health/generation-pipeline'
      fullPath: '/api/public/health/generation-pipeline'
      preLoaderRoute: typeof ApiPublicHealthGenerationPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/core-v4-run': {
      id: '/api/public/debug/core-v4-run'
      path: '/api/public/debug/core-v4-run'
      fullPath: '/api/public/debug/core-v4-run'
      preLoaderRoute: typeof ApiPublicDebugCoreV4RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/core-v4-render': {
      id: '/api/public/debug/core-v4-render'
      path: '/api/public/debug/core-v4-render'
      fullPath: '/api/public/debug/core-v4-render'
      preLoaderRoute: typeof ApiPublicDebugCoreV4RenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/core-v3-run': {
      id: '/api/public/debug/core-v3-run'
      path: '/api/public/debug/core-v3-run'
      fullPath: '/api/public/debug/core-v3-run'
      preLoaderRoute: typeof ApiPublicDebugCoreV3RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/build-status': {
      id: '/api/public/debug/build-status'
      path: '/api/public/debug/build-status'
      fullPath: '/api/public/debug/build-status'
      preLoaderRoute: typeof ApiPublicDebugBuildStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/build-marker': {
      id: '/api/public/debug/build-marker'
      path: '/api/public/debug/build-marker'
      fullPath: '/api/public/debug/build-marker'
      preLoaderRoute: typeof ApiPublicDebugBuildMarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/astro-probe': {
      id: '/api/public/debug/astro-probe'
      path: '/api/public/debug/astro-probe'
      fullPath: '/api/public/debug/astro-probe'
      preLoaderRoute: typeof ApiPublicDebugAstroProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GeneratingRoute: GeneratingRoute,
  PrivacyRoute: PrivacyRoute,
  SampleRoute: SampleRoute,
  TermsRoute: TermsRoute,
  DownloadReportTokenRoute: DownloadReportTokenRoute,
  ResultReportTokenRoute: ResultReportTokenRoute,
  ApiPublicDebugAstroProbeRoute: ApiPublicDebugAstroProbeRoute,
  ApiPublicDebugBuildMarkerRoute: ApiPublicDebugBuildMarkerRoute,
  ApiPublicDebugBuildStatusRoute: ApiPublicDebugBuildStatusRoute,
  ApiPublicDebugCoreV3RunRoute: ApiPublicDebugCoreV3RunRoute,
  ApiPublicDebugCoreV4RenderRoute: ApiPublicDebugCoreV4RenderRoute,
  ApiPublicDebugCoreV4RunRoute: ApiPublicDebugCoreV4RunRoute,
  ApiPublicHealthGenerationPipelineRoute:
    ApiPublicHealthGenerationPipelineRoute,
  ApiPublicJobsProcessGenerationRoute: ApiPublicJobsProcessGenerationRoute,
  ApiPublicJobsResendReadyEmailRoute: ApiPublicJobsResendReadyEmailRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
