/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SampleRouteImport } from './routes/sample'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultReportTokenRouteImport } from './routes/result.$reportToken'
import { Route as DownloadReportTokenRouteImport } from './routes/download.$reportToken'
import { Route as ApiHealthGenerationPipelineRouteImport } from './routes/api/health/generation-pipeline'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicJobsResendReadyEmailRouteImport } from './routes/api/public/jobs/resend-ready-email'
import { Route as ApiPublicJobsProcessGenerationRouteImport } from './routes/api/public/jobs/process-generation'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleRoute = SampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultReportTokenRoute = ResultReportTokenRouteImport.update({
  id: '/result/$reportToken',
  path: '/result/$reportToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadReportTokenRoute = DownloadReportTokenRouteImport.update({
  id: '/download/$reportToken',
  path: '/download/$reportToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthGenerationPipelineRoute =
  ApiHealthGenerationPipelineRouteImport.update({
    id: '/api/health/generation-pipeline',
    path: '/api/health/generation-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsResendReadyEmailRoute =
  ApiPublicJobsResendReadyEmailRouteImport.update({
    id: '/api/public/jobs/resend-ready-email',
    path: '/api/public/jobs/resend-ready-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsProcessGenerationRoute =
  ApiPublicJobsProcessGenerationRouteImport.update({
    id: '/api/public/jobs/process-generation',
    path: '/api/public/jobs/process-generation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/generating': typeof GeneratingRoute
  '/privacy': typeof PrivacyRoute
  '/sample': typeof SampleRoute
  '/terms': typeof TermsRoute
  '/download/$reportToken': typeof DownloadReportTokenRoute
  '/result/$reportToken': typeof ResultReportTokenRoute
  '/api/health/generation-pipeline': typeof ApiHealthGenerationPipelineRoute
  '/api/public/jobs/process-generation': typeof ApiPublicJobsProcessGenerationRoute
  '/api/public/jobs/resend-ready-email': typeof ApiPublicJobsResendReadyEmailRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/generating': typeof GeneratingRoute
  '/privacy': typeof PrivacyRoute
  '/sample': typeof SampleRoute
  '/terms': typeof TermsRoute
  '/download/$reportToken': typeof DownloadReportTokenRoute
  '/result/$reportToken': typeof ResultReportTokenRoute
  '/api/health/generation-pipeline': typeof ApiHealthGenerationPipelineRoute
  '/api/public/jobs/process-generation': typeof ApiPublicJobsProcessGenerationRoute
  '/api/public/jobs/resend-ready-email': typeof ApiPublicJobsResendReadyEmailRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/generating': typeof GeneratingRoute
  '/privacy': typeof PrivacyRoute
  '/sample': typeof SampleRoute
  '/terms': typeof TermsRoute
  '/download/$reportToken': typeof DownloadReportTokenRoute
  '/result/$reportToken': typeof ResultReportTokenRoute
  '/api/health/generation-pipeline': typeof ApiHealthGenerationPipelineRoute
  '/api/public/jobs/process-generation': typeof ApiPublicJobsProcessGenerationRoute
  '/api/public/jobs/resend-ready-email': typeof ApiPublicJobsResendReadyEmailRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/generating'
    | '/privacy'
    | '/sample'
    | '/terms'
    | '/download/$reportToken'
    | '/result/$reportToken'
    | '/api/health/generation-pipeline'
    | '/api/public/jobs/process-generation'
    | '/api/public/jobs/resend-ready-email'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/generating'
    | '/privacy'
    | '/sample'
    | '/terms'
    | '/download/$reportToken'
    | '/result/$reportToken'
    | '/api/health/generation-pipeline'
    | '/api/public/jobs/process-generation'
    | '/api/public/jobs/resend-ready-email'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/generating'
    | '/privacy'
    | '/sample'
    | '/terms'
    | '/download/$reportToken'
    | '/result/$reportToken'
    | '/api/health/generation-pipeline'
    | '/api/public/jobs/process-generation'
    | '/api/public/jobs/resend-ready-email'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GeneratingRoute: typeof GeneratingRoute
  PrivacyRoute: typeof PrivacyRoute
  SampleRoute: typeof SampleRoute
  TermsRoute: typeof TermsRoute
  DownloadReportTokenRoute: typeof DownloadReportTokenRoute
  ResultReportTokenRoute: typeof ResultReportTokenRoute
  ApiHealthGenerationPipelineRoute: typeof ApiHealthGenerationPipelineRoute
  ApiPublicJobsProcessGenerationRoute: typeof ApiPublicJobsProcessGenerationRoute
  ApiPublicJobsResendReadyEmailRoute: typeof ApiPublicJobsResendReadyEmailRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$reportToken': {
      id: '/result/$reportToken'
      path: '/result/$reportToken'
      fullPath: '/result/$reportToken'
      preLoaderRoute: typeof ResultReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$reportToken': {
      id: '/download/$reportToken'
      path: '/download/$reportToken'
      fullPath: '/download/$reportToken'
      preLoaderRoute: typeof DownloadReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/generation-pipeline': {
      id: '/api/health/generation-pipeline'
      path: '/api/health/generation-pipeline'
      fullPath: '/api/health/generation-pipeline'
      preLoaderRoute: typeof ApiHealthGenerationPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/resend-ready-email': {
      id: '/api/public/jobs/resend-ready-email'
      path: '/api/public/jobs/resend-ready-email'
      fullPath: '/api/public/jobs/resend-ready-email'
      preLoaderRoute: typeof ApiPublicJobsResendReadyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/process-generation': {
      id: '/api/public/jobs/process-generation'
      path: '/api/public/jobs/process-generation'
      fullPath: '/api/public/jobs/process-generation'
      preLoaderRoute: typeof ApiPublicJobsProcessGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GeneratingRoute: GeneratingRoute,
  PrivacyRoute: PrivacyRoute,
  SampleRoute: SampleRoute,
  TermsRoute: TermsRoute,
  DownloadReportTokenRoute: DownloadReportTokenRoute,
  ResultReportTokenRoute: ResultReportTokenRoute,
  ApiHealthGenerationPipelineRoute: ApiHealthGenerationPipelineRoute,
  ApiPublicJobsProcessGenerationRoute: ApiPublicJobsProcessGenerationRoute,
  ApiPublicJobsResendReadyEmailRoute: ApiPublicJobsResendReadyEmailRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
